### ISSUE TITLE
Не произносятся короткие фразы и предложения.

### ISSUE THREAD

**Issue by zertyuiop** [Balamoote/gtts-dic#1]
На самом деле ошибок несколько:
1. Если есть отдельностоящие короткие предложения или фразы в диалогах (например -Как? -Что? А? и подобные) а также схожие короткие предложения, то чтение на пару секунд приостанавливается, после чего со следующего предложения (если оно такое же короткое, то вновь замирает).
2. Отдельностоящие цифры/числа/буквы также не читаются, например в построчной таблице
(Курица 1
Утка 3
Индюк 6)

**Comment by Balamoote** [comment]
К сожалению, не заметил сразу.
Проверяю на AlreaderX.
1. Со словарем, точнее с его размером, связана только первая пауза при начале чтения текста (грузится и парсится ). Далее - почти наверняка косяки читалки, такое точно есть у Алридера привыборе некоторых настроек пауз между абзацами. Всё руки не дойдут описать это нормально и сообщить автору алридера.
Если наблюдаются паузы в других случаях, то просто не тянет устройство. Тут есть 3 варианта:
- сменить устройство на более современное, если дело в нём (вдруг, есть необходимость это сделать по другой причине);
- сменить читалку, возможно это ее косяк.

- воспользоваться скриптом из соседнего репозитария: ./get-words.sh -old book.fb2 (или -ld если с обработкой книги.)

Это создаст локальный словарь для конкретной книги, который будет сильно меньше по размеру. Если, например, планируется к прочтению 2 книги, то можно сделать 2 таких словарей и, чтобы не грузить их по отдельности просто склеить в один файл: cat dic1.lexx dic2.lexx | sort -u > local2dic.lexx
Обязательно отсортировать и удалить повторяющиеся строки! (эта опция сейчас сломана - сейчас буду чинить)
Уменьшать размер словаря не планирую в принципе, например, удаляя слова, кторые и так произносятся правильно (по времени это просто не реалистично). Когда гуглоговорилка потеряет актуальность, этот словарь будет основой для обработки текста для любого движка.

2. не могу вопроизвести. Есть 2 случая, когда подавляется произношение цифр:
regex"\d+\]"="-"
regex"\d+\}"="-"
т.е. перед квадратной и фигуной скобкой. Это сделано, чтобы по 2 раза не читались номера сносок. Фича, не баг.

**Comment by zertyuiop** [comment]
По 1 пункту, сам пользуюсь AlReader/AlreaderX, при использовании первое предложение вообще часто читается как белиберда (видимо на английском), дальше нормально. Я проверял на других читалках, там тоже есть проблема с чтением коротких предложений, но с той же частотой или нет, не помню, нет возможности нормально проверить, как вы уже отметили, пора менять устройство, у текущего умер аккумулятор и экран отклеился, хотя мощности должно хватать, там Snapdragon 845. Я также попробовал сделать сброс TTSLexx, но поведение осталось тем же, так что скорее всего возможно это либо баг TTSLexx, либо Google Speech Engine. По второму пункту не принципиально, оно тоже не всегда встречается, я даже в код самой книги залазил, на первый взгляд одинаково, но в каких-то местах читает, а в каких-то нет.

**Comment by Balamoote** [comment]
Возможно, что и TTSLexx. Он не идеален, но уникален и замены ему нет...
Скрипт get-words.sh починил...
В целом по поводу ошибок. Каждая версия словаря проходит проверку, чтобы ничто ни с чем не конфликтовало, но раздел REGEX никаких автоматических проверок не проходит. Если встречаются такие вот странности, то желательно перепроверить вообще без словаря и потом без блока REGEX.
